#!/usr/bin/env bash
# PreToolUse hook for Dusk Studio.
#
# Fires before Bash tool calls. If the command is a git commit / git push /
# gh pr create, reminds the assistant to give the change set a commit-hygiene
# pass and strip leftover scaffolding BEFORE the operation proceeds. Unlike the
# MANUAL.md check this fires for every commit/push regardless of which files
# changed — the hygiene pass is unconditional.

set -e

input=$(cat)

tool=$(echo "$input" | jq -r '.tool_name // ""')
if [ "$tool" != "Bash" ]; then
  exit 0
fi

cmd=$(echo "$input" | jq -r '.tool_input.command // ""')
if ! echo "$cmd" | grep -qE '(^|[^a-zA-Z])(git[[:space:]]+commit|git[[:space:]]+push|gh[[:space:]]+pr[[:space:]]+create)'; then
  exit 0
fi

msg='COMMIT_HYGIENE: before this commit/push/PR proceeds, review the change set (git diff --cached for a commit, git diff @{u}...HEAD for a push) and strip anything that would not survive review:
  - comments that restate what the code does, or narrate the change/PR/conversation (no "now also handle X", "per the review", task/round numbers)
  - comment density above the surrounding code; explanations of self-evident code
  - dead code, commented-out blocks, leftover debug logging, unused includes/vars from the edit
  - backwards-compat shims, "// removed" markers, vars renamed only to suppress warnings
  - defensive checks / abstractions added on spec with no current caller
  - emoji, "generated by", marketing/hype tone; commit bodies that narrate the session instead of describing the change
KEEP load-bearing comments (hidden invariants, RT-safety rationale, specific-bug workarounds). Test: would a senior dev leave this in review? If no, cut it. State in your response that the hygiene pass ran.'

jq -n --arg ctx "$msg" '{hookSpecificOutput: {hookEventName: "PreToolUse", additionalContext: $ctx}}'
