#!/usr/bin/env bash
# PreToolUse hook for Dusk Studio.
#
# Fires before Bash tool calls. If the command is a git commit / git push /
# gh pr create it does two things before the operation proceeds:
#   1. Mechanically scans the added lines of the relevant diff for
#      high-precision slop (Unicode typography + edit/task-reference tags) and
#      surfaces exact file:line hits.
#   2. Reminds the assistant to give the change set a judgement-level hygiene
#      pass for the categories a grep can't catch (restating comments, change
#      narration, dead code, on-spec defensiveness).
# Unlike the MANUAL.md check this fires for every commit/push regardless of
# which files changed - the hygiene pass is unconditional.

set -e

input=$(cat)

tool=$(echo "$input" | jq -r '.tool_name // ""')
if [ "$tool" != "Bash" ]; then
  exit 0
fi

cmd=$(echo "$input" | jq -r '.tool_input.command // ""')
if ! echo "$cmd" | grep -qE '(^|[^a-zA-Z])(git[[:space:]]+commit|git[[:space:]]+push|gh[[:space:]]+pr[[:space:]]+create)'; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || true

# Pick the diff that matches the operation about to run.
if echo "$cmd" | grep -qE '(^|[^a-zA-Z])git[[:space:]]+commit'; then
  DIFF=(git diff --cached --no-color -U0)
elif echo "$cmd" | grep -qE '(^|[^a-zA-Z])git[[:space:]]+push'; then
  if git rev-parse --abbrev-ref '@{u}' >/dev/null 2>&1; then
    DIFF=(git diff --no-color -U0 '@{u}..HEAD')
  else
    DIFF=(git diff --no-color -U0 'HEAD~5..HEAD')
  fi
else
  base=origin/main
  git rev-parse --verify "$base" >/dev/null 2>&1 || base=main
  DIFF=(git diff --no-color -U0 "${base}...HEAD")
fi

# Walk the diff, resolving each added line to file:newlineno, then match only
# high-precision patterns. Deliberately NOT flagged: math notation (≈ ∝ ² − ×),
# which is legitimate in DSP comments.
#   Typography  : em/en dash, arrows, bullet, ellipsis, smart quotes
#   Edit tags   : Hn: hypothesis labels, "(this commit)", roadmap step/increment refs
#   Session leak: "as requested" / "per the review" / "as discussed", "generated by",
#                 "Co-Authored", robot emoji
PATTERN='[—–→⇒•…“”‘’]|\bH[0-9]+:|\(this commit\)|\b(step|increment)[[:space:]]+[0-9]|\bas requested\b|per the review|as discussed|generated by|Co-Authored|🤖'

hits=$("${DIFF[@]}" -- '*.cpp' '*.h' '*.hpp' '*.mm' '*.c' '*.cc' 2>/dev/null | awk '
  /^\+\+\+ /      { sub(/^\+\+\+ b\//,""); f=$0; next }
  /^@@ /          { match($0, /\+[0-9]+/); ln=substr($0,RSTART+1,RLENGTH-1)+0; next }
  /^\+/           { print f ":" ln ":" substr($0,2); ln++; next }
' | grep -nP "$PATTERN" 2>/dev/null | cut -d: -f2- | head -n 60 || true)

detected=""
if [ -n "$hits" ]; then
  detected="

COMMIT_HYGIENE_DETECTED: the following ADDED lines contain slop this pass must resolve (fix or explicitly justify each before proceeding). Unicode typography -> ASCII (— -> -/--, → -> ->, • -> -, … -> ...); delete edit/task-reference tags (Hn:, \"(this commit)\", step/increment/roadmap refs, \"as requested\", \"generated by\", emoji):
$hits"
fi

msg='COMMIT_HYGIENE: before this commit/push/PR proceeds, review the change set (git diff --cached for a commit, git diff @{u}...HEAD for a push) and strip anything that would not survive review:
  - comments that restate what the code does (e.g. "// Get bass note" above the getter), or narrate the change/PR/conversation ("now we...", "no longer...", "used to...", "previously...", "after the refactor", "per the review", task/round/phase/step numbers)
  - Unicode typography in comments/strings: em/en dashes, arrows, bullets, ellipses, smart quotes -> plain ASCII. Keep genuine math glyphs (≈ ∝ ² − ×).
  - comment density above the surrounding code; explanations of self-evident code
  - dead code, commented-out blocks, stale comments describing behaviour the code no longer has, leftover debug logging, unused includes/vars from the edit
  - backwards-compat shims, "// removed" markers, vars renamed only to suppress warnings
  - defensive checks / abstractions added on spec with no current caller
  - emoji, "generated by", marketing/hype tone; commit bodies that narrate the session instead of describing the change
KEEP load-bearing comments (hidden invariants, RT-safety rationale, specific-bug workarounds). Test: would a senior dev leave this in review? If no, cut it. State in your response that the hygiene pass ran.'

jq -n --arg ctx "${msg}${detected}" '{hookSpecificOutput: {hookEventName: "PreToolUse", additionalContext: $ctx}}'
